### ISSUE TITLE
Failed to compile. :-(

### ISSUE THREAD

**Issue by roadapathy** [yvt/terravox#13]
/usr/lib/x86_64-linux-gnu/qt4/bin/uic erosioneditor.ui -o ui_erosioneditor.h
g++ -c -m64 -pipe -msse4.1 -mssse3 -msse3 -msse2 -msse -Wno-missing-braces -O2 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I. -o main.o main.cpp
main.cpp:69:9: warning: identifier ‘nullptr’ is a keyword in C++11 [-Wc++0x-compat]
         QMessageBox::critical(nullptr, a.applicationName(),
         ^
In file included from main.cpp:1:0:
mainwindow.h:66:36: error: ‘std::function’ has not been declared
     bool makeSureEffectIsDone(std::function<void(bool)> callback);
                                    ^
mainwindow.h:66:44: error: expected ‘,’ or ‘...’ before ‘<’ token
     bool makeSureEffectIsDone(std::function<void(bool)> callback);
                                            ^
mainwindow.h:71:28: error: ‘std::function’ has not been declared
     bool confirmClose(std::function<void(bool)> callback);
                            ^
mainwindow.h:71:36: error: expected ‘,’ or ‘...’ before ‘<’ token
     bool confirmClose(std::function<void(bool)> callback);
                                    ^
mainwindow.h:72:31: error: ‘std::function’ has not been declared
     bool saveInteractive(std::function<void(bool)> callback);
                               ^
mainwindow.h:72:39: error: expected ‘,’ or ‘...’ before ‘<’ token
     bool saveInteractive(std::function<void(bool)> callback);
                                       ^
mainwindow.h:73:33: error: ‘std::function’ has not been declared
     void saveAsInteractive(std::function<void(bool)> callback);
                                 ^
mainwindow.h:73:41: error: expected ‘,’ or ‘...’ before ‘<’ token
     void saveAsInteractive(std::function<void(bool)> callback);
                                         ^
mainwindow.h:82:34: warning: override controls (override/final) only available with -std=c++11 or -std=gnu++11
     void closeEvent(QCloseEvent *) override;
                                  ^
In file included from main.cpp:5:0:
cpu.h:8:5: warning: scoped enums only available with -std=c++11 or -std=gnu++11
     enum class Feature
     ^
cpu.h:25:20: warning: variadic templates only available with -std=c++11 or -std=gnu++11
     template <class...T>
                    ^
cpu.h:26:40: warning: variadic templates only available with -std=c++11 or -std=gnu++11
     bool supports(Feature feature, T...rest)
                                        ^
main.cpp: In function ‘int main(int, char**)’:
main.cpp:68:33: error: ‘CpuId::Feature’ is not a class or namespace
     if (!CpuId::supports(CpuId::Feature::Sse, CpuId::Feature::Sse2)) {
                                 ^
main.cpp:68:54: error: ‘CpuId::Feature’ is not a class or namespace
     if (!CpuId::supports(CpuId::Feature::Sse, CpuId::Feature::Sse2)) {
                                                      ^
main.cpp:69:31: error: ‘nullptr’ was not declared in this scope
         QMessageBox::critical(nullptr, a.applicationName(),
                               ^
Makefile:480: recipe for target 'main.o' failed
make: *** [main.o] Error 1

**Comment by yvt** [comment]
Qt 5.4 or later is required to compile Terravox.

**Comment by roadapathy** [comment]
Oh wow, ok. Thank you! I'll try it.
