### ISSUE TITLE
Add an "eye dropper" to the color picker

### ISSUE THREAD

**Issue by damienflament** [yvt/terravox#14]
An eye dropper will allow to get the color of the block selected with the mouse into the color picker.

![post-4797-0-39794100-1475891896](https://cloud.githubusercontent.com/assets/2023682/23575720/42058c42-0092-11e7-9bbc-deac1f9013e9.jpg)

**Comment by yvt** [comment]
I think there's already one - try clicking somewhere on the terrain while holding Alt key.

**Comment by damienflament** [comment]
You're right. Holding the `Alt` key change the mouse pointer to an eyedropper and allow to capture the color of the selected block. It works with regardless of the selected tool.

But, I can't find any mention of this feature in the software nor in the README/Wiki of this repository.
