### ISSUE TITLE
Terravox as a Battlebuilder-like map editor for .75 and Openspades

### ISSUE THREAD

**Issue by kmsiapps** [yvt/terravox#18]
I believe that one of the strong point of AoS lies in user-made content, and easy map-buliding can contribute to making AoS' community more active.

It would be nice to have those functions in Terravox :
* Ability to edit non-heightmap maps
* Editing individual voxels by dragging (like MagicaVoxel)
* Inserting models(kvx, kv6)
* Editing map metadata(spawning area, Intels, extensions) easily with GUI

We already have a great client(OpenSpades), so now it would be content-creating tools' turn.

**Comment by damienflament** [comment]
You should look at [Goxel](http://guillaumechereau.github.io/goxel/). It's a generic voxel editor which has a beta support for VLX and KV6 format.
It has not been specifically made for heightmap editing, but it supports objects importing has layers.

I don't want to throw away Terravox. But it seems that it has not been designed for generic voxel editing. Moreover, the maintainer seems to not have so much time to work on this project.

Finally, I like the idea to have a simple but elegant and powerful heightmap editor which does not do so much things, but do it well !

**Comment by kmsiapps** [comment]
@damienflament Thanks. I thought more AoS-specific map editor would help AoS community, but I ignored someone have to _**make**_ it using one's own time.

Using Goxel and Magicavoxel instead will do, then. Hopefully we can help implement that function in Goxel.
