### ISSUE TITLE
Cannot open the plugins folder 

### ISSUE THREAD

**Issue by noway** [yvt/terravox#5]
When i go to `Tools->Open scripts folder` terravox gives me following error:
![scrot](https://cloud.githubusercontent.com/assets/2031472/6429364/26c12314-c030-11e4-9995-9df2c1baa4f5.png)
Meanwhile, no errors given by stdin/stderr, so this is all information i have.
This is linux system.
How to fix this?

**Comment by yvt** [comment]
a70842ae2215b2a15aa4bac05a89474df52ed03c fixes this issue.
