### ISSUE TITLE
Windows release missing platform plugin

### ISSUE THREAD

**Issue by rakiru** [yvt/terravox#9]
Using release 0.2, I get this error on start up:

```
---------------------------
Terravox
---------------------------
This application failed to start because it could not find or load the Qt platform plugin "windows".

Reinstalling the application may fix this problem.
---------------------------
OK   
---------------------------
```

I think it needs `platforms/qwindows.dll`:
- http://stackoverflow.com/questions/14144075/application-deployed-with-qt5-libraries-does-not-start-on-windows-7
- http://forum.qt.io/topic/22825/solved-failed-to-load-platform-plugin/14

**Comment by yvt** [comment]
Added qwindows.dll and qminimal.dll. Could you check if it's working?

**Comment by rakiru** [comment]
Putting `platforms/` in the main directory stops the error, but the process closes after a few seconds now.

I will try building it myself tomorrow and look into it.

**Comment by rakiru** [comment]
Never mind, I think that's happening because my processor supports SSE 4A, not SSE 4.1.

The platforms plugin issue is fixed if you move `platforms/` to the base directory, not the `plugins/` directory.
